Document: hdbc
Title: Debian hdbc Manual
Author: <insert document author here>
Abstract: This manual describes what hdbc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hdbc/hdbc.sgml.gz

Format: postscript
Files: /usr/share/doc/hdbc/hdbc.ps.gz

Format: text
Files: /usr/share/doc/hdbc/hdbc.text.gz

Format: HTML
Index: /usr/share/doc/hdbc/html/index.html
Files: /usr/share/doc/hdbc/html/*.html

  
